@startuml
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam nodesep 70
skinparam ranksep 80
skinparam shadowing false

package "Modelos (Domínio)" {
    class Usuario {
      - id: UUID
      - nome: string
      - funcao: EnumFuncao
      + autenticar(): bool
    }

    class Teste {
      - id: UUID
      - config: JSON
      - status: EnumStatus
      - iniciado_em: timestamp
      - instabilidade: JSON
      + calcularProgresso(): float
    }

    class Relatorio {
      - id: UUID
      - latencia_media: float
      - taxa_falhas: float
      - url_json: string
      + consolidarMétricas(): void
    }
}

package "Core (Lógica de Execução)" {
    class TestEngine {
        - activeWorkers: List<WorkerNode>
        + iniciarTeste(teste: Teste): void
        - orquestrarPuppeteer(): void
    }

    class WorkerNode {
        - instanceId: UUID
        + spawn(config: JSON): void
        + injectFailure(type: string): void
        + collectRTCStats(): MetricasRaw
    }

    class SocketManager {
        + broadcastMetric(data: JSON): void
        + notifyCompletion(id: UUID): void
    }
}

package "Integração & Estratégia" {
    class ProviderFactory {
        + {static} createProvider(url: string): IConferenceProvider
    }

    interface IConferenceProvider {
        + {static} matches(url: string): boolean
        + name: string
        + requiresAccessToken(): boolean
        + isMultiPage(): boolean
        + getStats(page, browser): MetricasRaw
    }

    class WebRTCProvider implements IConferenceProvider
    class JitsiProvider implements IConferenceProvider
    class WherebyProvider implements IConferenceProvider
    class ZoomProvider implements IConferenceProvider
}

' Relacionamentos
Usuario "1" -- "*" Teste : solicita >
Teste "1" -- "0..1" Relatorio : gera >

TestEngine "1" *-- "*" WorkerNode : gerencia >
WorkerNode --> ProviderFactory : usa >
ProviderFactory ..> IConferenceProvider : cria >
TestEngine ..> SocketManager : live data >
WorkerNode ..> SocketManager : telemetria >
@enduml