@startuml
hide footbox
skinparam ParticipantPadding 20
skinparam MaxMessageSize 150

actor "Equipe Ágil" as Equipe
participant "Interface de\nRelatórios" as Web
participant "ReportGenerator\n(Service)" as Generator
database "PostgreSQL" as DB

Equipe -> Web: Solicita exportação (ID, Formato)
activate Web
Web -> Generator: GET /api/export/:uuid?format=csv
activate Generator

Generator -> DB: SELECT Metrics WHERE test_id = UUID
activate DB
DB --> Generator: Dataset de Telemetria
deactivate DB

Generator -> Generator: Agregar Dados (Média QoE, Falhas)
Generator -> Generator: Aplicar Estratégia de Formatação (CSV/JSON)

Generator --> Web: Stream do arquivo processado
deactivate Generator
Web --> Equipe: Download do Relatório Analítico
deactivate Web
@enduml