@startuml
hide footbox
skinparam ParticipantPadding 20

actor "Usuário" as User
participant "Sistema\nStreamSentry" as Sistema

User -> Sistema: realizarLogin(email, senha)
activate Sistema
Sistema -> Sistema: Validar credenciais

alt Credenciais válidas
    Sistema -> Sistema: Gerar Token JWT
    Sistema --> User: Token de Acesso (Sessão Iniciada)
else Credenciais inválidas
    Sistema --> User: Erro de autenticação (credenciais inválidas)
end
deactivate Sistema
@enduml
