@startuml
hide footbox
skinparam ParticipantPadding 20

actor "Tech Lead" as TechLead
participant "Sistema\nStreamSentry" as Sistema

TechLead -> Sistema: solicitarRelatorio(idTeste, formato)
activate Sistema

Sistema -> Sistema: Recuperar histórico e consolidar métricas
Sistema -> Sistema: Formatar arquivo (JSON/CSV)

Sistema --> TechLead: Download do arquivo (JSON/CSV)
deactivate Sistema
@enduml
